### ISSUE TITLE
docker :WARNING: No database support: ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#11503]
how start postgresql
and connect postgresql
```
git clone https://github.com/rapid7/metasploit-framework
cd metasploit-framework
docker build --rm -t metasploit-framework .
docker rm msf5_github
docker run -it -P -v /tmp/.X11-unix:/tmp/.X11-unix --name='msf5_github' metasploit-framework /bin/sh

# in docker
/usr/src/metasploit-framework $ ./msfconsole

[-] ***rting the Metasploit Framework console...|
[-] * WARNING: No database support: ActiveRecord::ConnectionNotEstablished
[-] ***

 workspace -v
[-] Database not connected
msf5 > db_status
[*] postgresql selected, no connection

/usr/src/metasploit-framework $ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 06:43 pts/0    00:00:00 /bin/bash docker/entrypoint.sh /bin/sh
msf         13     1  0 06:43 pts/0    00:00:00 /bin/sh


```

**Comment by hktalent** [comment]
in docker
```
/usr/src/metasploit-framework $ find / -name "*post*" 2>/dev/null |grep -Ev "metasploit|bundle|python"
/sys/module/kernel/parameters/crash_kexec_post_notifiers
/etc/network/if-post-up.d
/etc/network/if-post-down.d

```

**Comment by akiraaranii** [comment]
How about Segmentation Fault??

**Comment by hktalent** [comment]
```
Dockerfile
line 33 +
FROM postgres:11.2-alpine

wget -c https://raw.githubusercontent.com/docker-library/postgres/6c3b27f1433ad81675afb386a182098dc867e3e8/11/alpine/docker-entrypoint.sh docker/
cat docker-entrypoint.sh entrypoint.sh >>entrypoint1.sh

# change:
ENTRYPOINT ["docker/entrypoint1.sh"]

cd ..
docker build --rm -t metasploit-framework .

```

**Comment by hktalent** [comment]
```
# run postgres in other docker
docker run -p 5432:5432 --name msf -e POSTGRES_PASSWORD=msf -e POSTGRES_USER=msf -e POSTGRES_DB=msf -d postgres:11.2-alpine

psql "postgres://msf@172.17.0.3:5432/msf"
```

**Comment by hktalent** [comment]
```
cat  ~/.msf4/database.yml
development: &pgsql
  adapter: postgresql
  database: msf
  username: msf
  password: msf
  host: 172.17.0.3
  port: 5432
  pool: 200
  timeout: 5

production: &production
  <<: *pgsql

test:
  <<: *pgsql
  database: msftest
  username: msftest
  password: pVqd21vtKi/oWVZGeBPyeckJtE3y8qLjjtb3xw+eI20=


```
