### ISSUE TITLE
Ability to filter the --list output

### ISSUE THREAD

**Issue by noraj** [rapid7/metasploit-framework#12250]
```yaml
tags : [msfvenom, feature request]
priority : low
easiness : easy  || medium
```

## Description

When running `msfvenom --list payloads --platform linux` it lists all payloads (for linux, java, osx, windows, etc.), it would be great that when `--platform` is used it filter the `--list` output.

This could avoid the usage of `grep 'linux/'` or more complex patterns when waiting to filter through several criteria `payloads, encoders, nops, platforms, archs, encrypt, formats, all`.

Ex:

- payloads could be filtered by platform, archs
- encoders could be filtered by archs
- maybe more
