### ISSUE TITLE
How to use a remote PostgreSQL database?

### ISSUE THREAD

**Issue by FalcoGer** [rapid7/metasploit-framework#17976]
## Summary
I am running metasploit on ubuntu, installed from the ppa at http://downloads.metasploit.com/data/releases/metasploit-framework/apt.

I wish to use multiple metasploit instances on different machines but use the same database on my local network. I changed `~/.msf4/database.yml` to this configuration:

```yaml
# To set up a metasploit database, follow the directions hosted at:
# http://r-7.co/MSF-DEV#set-up-postgresql
#
# Kali Linux and the Omnibus installers both include an easy wrapper script for
# managing your database, which may be more convenient than rolling your own.

development: &pgsql
  adapter: postgresql
  database: msf
  username: msf
  password: password_for_msf
  host: hostname_for_database_host.lan
  port: 5432
  pool: 200
  timeout: 5

# You will often want to seperate your databases between dev
# mode and prod mode. Absent a production db, though, defaulting
# to dev is pretty sensible for many developer-users.
production: &production
  <<: *pgsql

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#
# Note also, sqlite3 is totally unsupported by Metasploit now.
test:
  <<: *pgsql
  database: msftest
```

However, when I do `msfdb init` or `msfdb reinit` it would create a local postgresql instance in `~/.msf4/db/` and launch that and it would replace the host line in the database.yml file with `host: 127.0.0.1`.

How do I run metasploit on a remote database and how do I initialize it with all the proper tables?

Also I have a mysql database already running (on the remote host) and would prefer to use that instead of spinning up postgres. Is that possible? If so, how do I set that up instead?
