### ISSUE TITLE
Create an official docker image

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#5284]
What do you guys think if we create a default docker image for metasploit containing a preconfigured working installation? I have found several user based containers, but no official one.

What do you think? I would love to implement a metasploit install in docker for a easy way to run it if you think it's worth it.

We would need a new github repo for the Dockerfile and a metasploit organization on https://hub.docker.com/

**Comment by mubix** [comment]
I have done this a few times with different installs (Pro trial, framework and Community). I'd be keen on taking this on, make a clean image for each and push them, with a few tutorials on how to get them going

**Comment by FireFart** [comment]
@mubix so if there is a agreement on creating a docker image, maybe we should start a document meet in irc to discuss the implementation details like use rvm or rbenv and such things

**Comment by UserTaken** [comment]
I created [usertaken/metasploit-framework](https://registry.hub.docker.com/u/usertaken/metasploit-framework) after watching [Metasploit Minute](https://www.patreon.com/mubix) so I would be interested on how an official image would be created.

**Comment by timwr** [comment]
Nice one @usertaken. I've played with  github.com/infoslack/docker-metasploit but yours looks neater as it's a single container with both metasploit and postgresql.

**Comment by UserTaken** [comment]
I included PostgreSQL for convenience but alternatively something like 

```
containers:
  loot:
      image: busybox
      run:
          volume: ["/opt/metasploit-framework/.msf4", "/var/www", "/tmp"]
          cmd: ["watch", "-n", "120", "-t", "ls", "-pArcelhR", "--color=always", "/opt/metasploit-framework/.msf4"]
          detach: true

  database:
      image: postgres:latest
      run:
          env: ["POSTGRES_PASSWORD=msf"]
          publish: ["127.0.0.1:5432:5432"]
          detach: true

  adminer:
      image: clue/adminer
      run:
          link: ["database:postgres"]
          publish: ["127.0.0.1:8080:80"]
          detach: true

  metasploit:
      image: usertaken/metasploit-framework
      run:
          net: host
          tty: true
          interactive: true
          volumes-from: ["loot"]
          cmd: ["/bin/bash"]

``` 
with [Crane](https://github.com/michaelsauter/crane) can be used to spread things out. This is one of the things that need to be addressed for an official Metasploit image.
